services:
  - type: web
    name: nebula
    env: node
    buildCommand: cd master && npm install && cd ../frontend && npm install && npm run build && cd ..
    startCommand: cd master && node index.js
    envVars:
      - key: NODE_ENV
        value: production
